---

- name: Update
  shell: notify-send -a Shack WeeChat "Starting role."
  changed_when: false

- name: Install weechat
  become: true
  dnf:
    name:
      - weechat

- name: Make sure the weechat directory is created
  command: weechat-headless -r "/quit"
  changed_when: false
  ignore_errors: true

- name: Download notify-send
  get_url:
    url: https://raw.githubusercontent.com/s3rvac/weechat-notify-send/master/notify_send.py
    dest: ~/.weechat/python/notify_send.py

- name: auto-load notify-send
  file:
    src: ~/.weechat/python/notify_send.py
    dest: ~/.weechat/python/autoload/notify_send.py
    state: link

- name: Download highmon
  get_url:
    url: https://raw.githubusercontent.com/KenjiE20/highmon/master/highmon.pl
    dest: ~/.weechat/perl/highmon.pl

- name: auto-load highmon
  file:
    src: ~/.weechat/perl/highmon.pl
    dest: ~/.weechat/perl/autoload/highmon.pl
    state: link

- name: Download autojoin
  get_url:
    url: https://weechat.org/files/scripts/autojoin.py
    dest: ~/.weechat/python/autojoin.py

- name: auto-load autojoin
  file:
    src: ~/.weechat/python/autojoin.py
    dest: ~/.weechat/python/autoload/autojoin.py
    state: link

- name: Download autosort
  get_url:
    url: https://raw.githubusercontent.com/de-vri-es/weechat-autosort/master/autosort.py
    dest: ~/.weechat/python/autosort.py

- name: auto-load autosort
  file:
    src: ~/.weechat/python/autosort.py
    dest: ~/.weechat/python/autoload/autosort.py
    state: link
