---
- name: Create user bin directory
  file:
    path: ~/bin
    state: directory
    mode: '0755'

- name: Copy over scripts
  copy:
    src: "{{ item }}"
    dest: ~/bin/{{ item | basename | regex_replace('\.j2','') }}
    mode: a+x
  with_fileglob:
    - ../templates/*
