- name: Create user bin directory
  file:
    path: ~/bin
    state: directory
    mode: '0755'

- name: Copy over scripts
  copy:
    src: "{{ item }}"
    dest: ~/bin/{{ item | basename | regex_replace('\.j2','') }}
    mode: a+x
  with_fileglob:
    - ../templates/*

- name: Delete mirrored repos
  file:
    path: ~/code/mirror/
    state: absent
  when:
    - very_slow is defined and very_slow|bool

- name: Updated cloned repos
  shell: ~/bin/cloneall
  changed_when: False
  when:
    - very_slow is defined and very_slow|bool
