- name: Install redshift
  become: true
  dnf:
    name:
      - redshift

- name: Create redshift config directory
  file:
    path: ~/.config/redshift
    state: directory
    mode: '0755'

- name: redshift config file
  copy:
    src: redshift.conf
    dest: ~/.config/redshift/redshift.conf
