---

- name: Update
  shell: notify-send -a Shack Fish "Starting role."
  changed_when: false

- name: Install fish
  become: true
  dnf:
    name:
      - fish

- name: Remoing fish greeting
  shell: fish -c 'set fish_greeting ""'
  args:
    executable: /usr/bin/fish
  changed_when: false

- name: Fish config file
  copy:
    src: ./templates/config.fish
    dest: ~/.config/fish/config.fish
