---

- name: Update
  shell: notify-send -a Shack Fish "Starting role."
  changed_when: False

- name: Install fish
  become: true
  dnf:
    name:
      - fish
    state: latest

- name: Remoing fish greeting
  shell: fish -c 'set fish_greeting ""'
  args:
    executable: /usr/bin/fish
  changed_when: False

- name: Fish config file
  template:
    src: config.fish.j2
    dest: ~/.config/fish/config.fish