---

- hosts: localhost
  tasks:
    - name: Handle errors
      block:
        - include_role:
            name: init
        - include_role:
            name: common
        - include_role:
            name: wmcommon
        - include_role:
            name: i3
        - include_role:
            name: vim
        - include_role:
            name: scripts
        - include_role:
            name: mpd
        - include_role:
            name: fish
        - include_role:
            name: weechat
        - include_role:
            name: python
        - include_role:
            name: vscode
        - include_role:
            name: redshift
        - include_role:
            name: javascript
        - include_role:
            name: ruby
        - include_role:
            name: go
        - include_role:
            name: gui_apps
        - name: Update
          shell: notify-send -u low -a Shack Finished "We are all done!"
          changed_when: False
      rescue:
        - name: Update
          shell: notify-send -u critical -a Shack Finished "Playbook failed!"
          changed_when: False
