---

- hosts: localhost
  tasks:
    - name: Handle errors
      block:
        - include_role:
            name: init
        - include_role:
            name: python
        - include_role:
            name: vim
        - include_role:
            name: fish
        - include_role:
            name: scripts
        - include_role:
            name: todoist
      rescue:
        - name: Update
          shell: notify-send -u critical -a Shack Finished "Playbook failed!"
          changed_when: False
