---
- name: Install Snaps
  become: true
  snap:
    name:
      - spotify
      - telegram-desktop
      - chromium

- name: Install Classic Snaps
  become: true
  snap:
    name:
      - slack
      - codium
    classic: yes

- name: Enable Zeal repo
  become: true
  apt_repository:
    repo: ppa:zeal-developers/ppa

- name: Install apt apps
  become: true
  apt:
    name:
      - zeal
      - virt-manager
      - network-manager-openvpn-gnome
      - gnome-session
      - gdm3
