---
- name: Install Snaps
  become: true
  snap:
    name:
      - spotify
      - telegram-desktop
      - chromium
      - discord
      - mattermost-desktop

- name: Install Classic Snaps
  become: true
  snap:
    name:
      - slack
      - codium
    classic: yes

- name: Enable Zeal repo
  become: true
  apt_repository:
    repo: ppa:zeal-developers/ppa

- name: Install apt apps
  become: true
  apt:
    name:
      - zeal
      - virt-manager
      - network-manager-openvpn-gnome
      - gnome-session
      - gdm3

- name: Plex media player
  get_url:
    url: https://knapsu.eu/data/plex/Plex_Media_Player_2.56.0.1071-85947843_x64.AppImage
    dest: ~/bin/plex-media-player

- name: chmod p-m-p
  file:
    path: ~/bin/plex-media-player
    mode: +x
