---
- name: Install Snaps
  become: true
  snap:
    name:
      - telegram-desktop
      - chromium
      - discord
      - mattermost-desktop
      - rpi-imager

- name: Install not really gui apps
  become: true
  snap:
    name:
      - matterhorn

- name: Install Classic Snaps
  become: true
  snap:
    name:
      - slack
      - codium
    classic: yes

- name: Add spotify key
  become: true
  apt_key:
    url: https://download.spotify.com/debian/pubkey.gpg
    state: present

- name: Enable spotify repo
  become: true
  apt_repository:
    repo: deb http://repository.spotify.com stable non-free
    state: present

- name: Install apt apps
  become: true
  apt:
    name:
      - virt-manager
      - network-manager-openvpn-gnome
      - gnome-session
      - gdm3
      - spotify-client

- name: Plex media player
  get_url:
    url: https://knapsu.eu/data/plex/Plex_Media_Player_2.56.0.1071-85947843_x64.AppImage
    dest: ~/bin/plex-media-player

- name: chmod p-m-p
  file:
    path: ~/bin/plex-media-player
    mode: +x
