---
- name: Install common core packages
  become: true
  dnf:
    name:
      - blueman
      - chromium
      - gimp
      - gitstats
      - inkscape
      - mediawriter
      - pavucontrol
      - workrave
      - workrave-gtk2
      - zeal

- name: Is Slack installed
  shell: >-
    rpm -qa slack
  args:
    warn: false
  register: slack_installed

- name: Slack client
  become: true
  dnf:
    name:
      - https://downloads.slack-edge.com/linux_releases/slack-4.1.2-0.1.fc21.x86_64.rpm
  when: slack_installed.stdout.find('slack') == -1

- name: Install Slack
  become: true
  dnf:
    name:
      - slack

- name: RPM Fusion
  become: true
  shell: >
    dnf install -y https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm;
    dnf install -y https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm;
  args:
    warn: false
  changed_when: False

- name: Install non-free
  become: true
  dnf:
    name:
      - '@Games and Entertainment'
      - dropbox
      - lpf-spotify-client
      - nautilus-dropbox
      - plex-media-player
      - steam

- name: Add user to the lpf group
  become: true
  user:
    name: dougal
    group: pkg-build
