---

- name: Update
  shell: notify-send -a Shack Python "Starting role."
  changed_when: False

- name: "Install pyenv and Python versions"
  include_role:
    name: avanov.pyenv
  vars:
    pyenv_path: "/home/dougal/.pyenv"
    pyenv_owner: "dougal"
    pyenv_global: "3.8.0 3.7.5 3.6.9 3.5.7 2.7.17"
    pyenv_update_git_install: yes
    pyenv_python_versions:
      - "3.8.0"
      - "3.7.5"
      - "3.6.9"
      - "3.5.7"
      - "2.7.17"
    pyenv_virtualenvs: []
    pyenv_setting_path: /home/dougal/.bashrc

- name: Upgrade pip
  shell: source /home/dougal/.pyenv/.pyenvrc && pip install -U pip
  changed_when: False

- name: Install pipx
  pip:
    name: pipx
    executable: ~/.pyenv/shims/pip
    state: latest

- name: Install pipx packages
  shell: ~/.pyenv/shims/pipx install {{ item }} --python=python3.8 --pip-args='--upgrade' --force
  with_items:
    - awscli
    - black
    - entry_point_inspector
    - flake8
    - git-review
    - httpie
    - livereload
    - mistral-lint
    - mkdocs
    - pipdeptree
    - pipenv
    - poetry
    - pynd
    - python-openstackclient
    - reno
    - towncrier
    - tox
    - vulture
    - yaql
    - flashfocus
  changed_when: False
