---

- name: Install some deps
  become: true
  apt:
    name:
      - liblzma-dev

- name: pyenv clean
  file:
    path: "/home/dougal/.pyenv"
    state: absent
  when:
    - very_slow is defined and very_slow|bool

- name: "Install pyenv and Python versions"
  include_role:
    name: avanov.pyenv
  vars:
    pyenv_path: "/home/dougal/.pyenv"
    pyenv_owner: "dougal"
    pyenv_global: "3.9.1 3.8.6 3.7.9 3.6.12 3.5.10 2.7.18"
    pyenv_update_git_install: yes
    pyenv_python_versions:
      - "3.9.1"
      - "3.8.6"
      - "3.7.9"
      - "3.6.12"
      - "3.5.10"
      - "2.7.18"
    pyenv_virtualenvs:
      - venv_name: "vim_py2"
        py_version: "2.7.18"
      - venv_name: "vim_py3"
        py_version: "3.9.1"
    pyenv_setting_path: /home/dougal/.bashrc

- name: Upgrade pip
  shell: ~/.pyenv/shims/pip install -U pip
  changed_when: False

- name: Install pipx
  pip:
    name: pipx
    executable: ~/.pyenv/shims/pip
    state: latest

- name: Remove any installed packages
  shell: ~/.pyenv/shims/pipx uninstall-all
  changed_when: False
  when:
    - very_slow is defined and very_slow|bool

- name: Upgrade all installed packages
  shell: ~/.pyenv/shims/pipx upgrade-all
  changed_when: False
  when:
    - very_slow is not defined

- name: Install pipx packages
  shell: ~/.pyenv/shims/pipx install {{ item }} --python=python3 --pip-args='--upgrade'
  with_items:
    - awscli
    - black
    - doc2dash
    - flake8
    - git-review
    - httpie
    - jenkins-job-builder
    - livereload
    - mkdocs
    - pip-tools
    - pipenv
    - poetry
    - pynd
    - super3
    - towncrier
    - tox
    - uvicorn
    - vulture
    - yamllint
  changed_when: False

- name: pipx inject
  shell: ~/.pyenv/shims/pipx inject mkdocs mkdocs-material
  changed_when: False

- name: vim inject pynvim
  shell: "{{ item }} install pynvim"
  with_items:
     - ~/.pyenv/versions/vim_py2/bin/pip
     - ~/.pyenv/versions/vim_py3/bin/pip
  changed_when: False

- name: vim inject black
  shell: "{{ item }} install black"
  with_items:
     - ~/.pyenv/versions/vim_py3/bin/pip
  changed_when: False
