---

- name: "Install pyenv and Python versions"
  include_role:
    name: avanov.pyenv
  vars:
    pyenv_path: "/home/dougal/.pyenv"
    pyenv_owner: "dougal"
    pyenv_global: "3.8.2 3.7.7 3.6.10 3.5.9 2.7.17"
    pyenv_update_git_install: yes
    pyenv_python_versions:
      - "3.8.2"
      - "3.7.7"
      - "3.6.10"
      - "3.5.9"
      - "2.7.17"
    pyenv_virtualenvs:
      - venv_name: "vim_py2"
        py_version: "2.7.17"
      - venv_name: "vim_py3"
        py_version: "3.8.2"
    pyenv_setting_path: /home/dougal/.bashrc

- name: Upgrade pip
  shell: ~/.pyenv/shims/pip install -U pip
  changed_when: False

- name: Install pipx
  pip:
    name: pipx
    executable: ~/.pyenv/shims/pip
    state: latest

- name: Remove any installed packages
  shell: ~/.pyenv/shims/pipx uninstall-all
  changed_when: False
  when:
    - pipx_clean is defined
    - pipx_clean|bool

- name: Install pipx packages
  shell: ~/.pyenv/shims/pipx install {{ item }} --python=python3 --pip-args='--upgrade' --force
  with_items:
    - awscli
    - black
    - doc2dash
    - entry_point_inspector
    - flake8
    - git-review
    - httpie
    - livereload
    - mkdocs
    - pip-tools
    - pipdeptree
    - pipenv
    - poetry
    - pynd
    - towncrier
    - tox
    - uvicorn
    - vulture
    - yamllint
    - yaql
  changed_when: False

- name: pipx inject
  shell: ~/.pyenv/shims/pipx inject mkdocs mkdocs-material
  changed_when: False

- name: vim inject pynvim
  shell: "{{ item }} install pynvim"
  with_items:
     - ~/.pyenv/versions/vim_py2/bin/pip
     - ~/.pyenv/versions/vim_py3/bin/pip
