---

- name: "Install pyenv and Python versions"
  include_role:
    name: avanov.pyenv
  vars:
    pyenv_path: "/home/dougal/.pyenv"
    pyenv_owner: "dougal"
    pyenv_global: "3.10.7"
    pyenv_update_git_install: yes
    pyenv_python_versions:
      - "3.10.7"
    pyenv_virtualenvs:
      - venv_name: "vim_py3"
        py_version: "3.10.7"
    pyenv_setting_path: /home/dougal/.bashrc

- name: Upgrade pip
  shell: ~/.pyenv/shims/pip install -U pip
  changed_when: False

- name: Install pipx
  pip:
    name: pipx
    executable: ~/.pyenv/shims/pip
    state: latest

- name: Remove any installed packages
  shell: ~/.pyenv/shims/pipx uninstall-all
  changed_when: False

- name: Upgrade all installed packages
  shell: ~/.pyenv/shims/pipx upgrade-all
  changed_when: False

- name: Install pipx packages
  shell: ~/.pyenv/shims/pipx install {{ item }} --python=python3
  with_items:
    - awscli
    - black
    - doc2dash
    - flake8
    - git-review
    - httpie
    - jenkins-job-builder
    - livereload
    - mkdocs
    - pip-tools
    - pipenv
    - poetry
    - pynd
    - radon
    - shotman
    - super3
    - towncrier
    - tox
    - uvicorn
    - vulture
    - yamllint
  changed_when: False

- name: pipx inject
  shell: ~/.pyenv/shims/pipx inject mkdocs mkdocs-material
  changed_when: False

- name: vim inject pynvim
  shell: "{{ item }} install pynvim"
  with_items:
     - ~/.pyenv/versions/vim_py3/bin/pip
  changed_when: False

- name: vim inject black
  shell: "{{ item }} install black"
  with_items:
     - ~/.pyenv/versions/vim_py3/bin/pip
  changed_when: False
