---
- name: Install i3 packages
  become: true
  dnf:
    name:
      - rofi
      - rxvt-unicode
      - alsa-utils
      - mate-power-manager
      - sway
      - sway-systemd
      - swaybg
      - swayidle
      - swaylock
      - waybar
      - grim
      - kanshi
      - wlsunset
      - wdisplays
      - mako

- name: Create i3 config directory
  file:
    path: ~/.config/i3
    state: directory
    mode: '0755'

- name: i3 config file
  copy:
    src: ./templates/i3.config
    dest: ~/.config/i3/config

- name: Create waybar config directory
  file:
    path: ~/.config/waybar
    state: directory
    mode: '0755'

- name: waybar config file
  copy:
    src: ./templates/waybar.config
    dest: ~/.config/waybar/config

- name: xinitrc
  copy:
    src: ./templates/xinitrc
    dest: ~/.xinitrc


- name: Create rofi config directory
  file:
    path: ~/.config/rofi
    state: directory
    mode: '0755'

- name: rofi theme
  copy:
    src: ./templates/rofi-config
    dest: ~/.config/rofi/config

- name: rofi theme
  copy:
    src: ./templates/rofi-theme
    dest: ~/.config/rofi/default.rasi
