---

- name: Update
  shell: notify-send -a Shack i3 "Starting role."

- name: Install i3 packages
  become: true
  dnf:
    name:
      - i3
      - i3lock
      - rofi
    state: latest

- name: Create i3 config directory
  file:
    path: ~/.config/i3
    state: directory
    mode: '0755'

- name: i3 config file
  template:
    src: i3.config.j2
    dest: ~/.config/i3/config