---
- name: Install i3 packages
  become: true
  dnf:
    name:
      - alsa-utils
      - grim
      - kanshi
      - mako
      - mate-power-manager
      - playerctl
      - rofi
      - rxvt-unicode
      - sway
      - sway-systemd
      - swaybg
      - swayidle
      - swaylock
      - waybar
      - wdisplays
      - wlsunset

- name: Install PyGObject dnf deps
  become: true
  dnf:
    name:
      - python3-gobject
      - gtk3
      - gcc
      - gobject-introspection-devel
      - cairo-gobject-devel
      - pkg-config
      - python3-devel
      - gtk3

- name: Install PyGObject pip deps
  pip:
    name:
      - pycairo
      - PyGObject

- name: Create i3 config directory
  file:
    path: ~/.config/i3
    state: directory
    mode: '0755'

- name: i3 config file
  copy:
    src: ./templates/i3.config
    dest: ~/.config/i3/config

- name: Create waybar config directory
  file:
    path: ~/.config/waybar
    state: directory
    mode: '0755'

- name: waybar config file
  copy:
    src: ./templates/waybar.config
    dest: ~/.config/waybar/config

- name: waybar css file
  copy:
    src: ./templates/waybar.css
    dest: ~/.config/waybar/style.css

- name: waybar mediaplayer script
  copy:
    src: ./templates/mediaplayer.py
    dest: ~/.config/waybar/mediaplayer.py

- name: Reload waybar config
  shell: killall -SIGUSR2 waybar

- name: Disable sleep
  become: true
  shell: systemctl status sleep.target suspend.target hibernate.target hybrid-sleep.target
  ignore_errors: yes

- name: Create kanshi config directory
  file:
    path: ~/.config/kanshi
    state: directory
    mode: '0755'

- name: kanshi config file
  copy:
    src: ./templates/kanshi.config
    dest: ~/.config/kanshi/config

- name: Create rofi config directory
  file:
    path: ~/.config/rofi
    state: directory
    mode: '0755'

- name: rofi theme
  copy:
    src: ./templates/rofi-config
    dest: ~/.config/rofi/config

- name: rofi theme
  copy:
    src: ./templates/rofi-theme
    dest: ~/.config/rofi/default.rasi
