---
- name: Install i3 packages
  become: true
  dnf:
    name:
      - compton
      - i3-gaps
      - i3lock
      - rofi
      - rxvt-unicode
      - alsa-utils
      - mate-power-manager
      - arandr

- name: Create i3 config directory
  file:
    path: ~/.config/i3
    state: directory
    mode: '0755'

- name: i3 config file
  copy:
    src: ./templates/i3.config
    dest: ~/.config/i3/config

- name: i3status config file
  copy:
    src: ./templates/i3status
    dest: ~/.config/i3/i3status

- name: Create compton config directory
  file:
    path: ~/.config/compton
    state: directory
    mode: '0755'

- name: compton config file
  copy:
    src: ./templates/compton.conf
    dest: ~/.config/compton/compton.conf

- name: xinitrc
  copy:
    src: ./templates/xinitrc
    dest: ~/.xinitrc


- name: Create rofi config directory
  file:
    path: ~/.config/rofi
    state: directory
    mode: '0755'

- name: rofi theme
  copy:
    src: ./templates/rofi-config
    dest: ~/.config/rofi/config

- name: rofi theme
  copy:
    src: ./templates/rofi-theme
    dest: ~/.config/rofi/default.rasi