---

- name: Update
  shell: notify-send -a Shack i3 "Starting role."

- name: polybar copr
  become: true
  command: dnf copr enable -y mhartgring/polybar
  args:
    warn: false

- name: i3-gaps copr
  become: true
  command: dnf copr enable -y nforro/i3-gaps
  args:
    warn: false

- name: Install i3 packages
  become: true
  dnf:
    name:
      - compton
      - i3-gaps
      - i3lock
      - rofi
      - polybar
      - rxvt
      - rxvt-unicode
      - alsa-utils
      - mate-power-manager
      - arandr

- name: Create i3 config directory
  file:
    path: ~/.config/i3
    state: directory
    mode: '0755'

- name: i3 config file
  copy:
    src: i3.config
    dest: ~/.config/i3/config

- name: Create polybar config directory
  file:
    path: ~/.config/polybar
    state: directory
    mode: '0755'

- name: Create polybar config directory
  file:
    path: ~/.config/polybar/scripts
    state: directory
    mode: '0755'

- name: polybar config file
  copy:
    src: polybar.config
    dest: ~/.config/polybar/config

- name: Polybar scripts
  copy:
    src: "{{ item }}"
    dest: ~/.config/polybar/scripts/{{ item | basename | regex_replace('\.j2','') }}
    mode: a+x
  with_fileglob:
    - ../templates/polybar-scripts/*

- name: polybar run file
  copy:
    src: polybar-run.sh
    dest: ~/.config/polybar/run.sh

- name: polybar run file +x
  file:
    dest: ~/.config/polybar/run.sh
    mode: a+x

- name: Create compton config directory
  file:
    path: ~/.config/compton
    state: directory
    mode: '0755'

- name: compton config file
  copy:
    src: compton.conf
    dest: ~/.config/compton/compton.conf

- name: xinitrc
  copy:
    src: xinitrc
    dest: ~/.xinitrc


- name: Create rofi config directory
  file:
    path: ~/.config/rofi
    state: directory
    mode: '0755'

- name: rofi theme
  copy:
    src: rofi-config
    dest: ~/.config/rofi/config

- name: rofi theme
  copy:
    src: rofi-theme
    dest: ~/.config/rofi/default.rasi
