---

- name: Update
  shell: notify-send -a Shack JavaScript "Starting role."
  changed_when: False

- name: Install npm packages
  become: true
  apt:
    name:
      - npm
      - nodejs

- name: Install neovim
  become: true
  npm:
    global: true
    name: neovim
