---
- name: Update
  shell: notify-send -a Shack JavaScript "Starting role."
  changed_when: false

- name: Install npm packages
  become: true
  dnf:
    name:
      - npm

- name: Install neovim
  become: true
  npm:
    global: true
    name: neovim
