---

- name: Install node packages
  become: true
  apt:
    name:
      - npm

- name: Install Snaps
  become: true
  snap:
    name: node
    channel: latest/edge
    classic: yes

- name: Install neovim
  become: true
  npm:
    global: true
    name: neovim
