#!/bin/bash -ex
#
# Create and start a bionic lxd with the home directory mounted


IMAGE="bionic"
NAME="$IMAGE-with-home-mounted"

ID=$(id -u)
SUBUID='root:$ID:1'

if ! grep -q $SUBUID /etc/subuid; then
    echo $SUBUID | sudo tee -a /etc/subuid /etc/subgid
fi

lxc init ubuntu:$IMAGE $NAME

lxc config set $NAME raw.idmap "both $ID $ID"

lxc config device add $NAME homedir disk source=$HOME path=/home/ubuntu

lxc start $NAME
