#!/bin/bash -ex
#
# Create and start a bionic lxd with the home directory mounted


IMAGE="bionic"
LXD_INSTANCE_NAME="$IMAGE-jenkins"
LXD_PROFILE="jenkins"

ID=$(id -u)
SUBUID='root:$ID:1'

if lxc info "$LXD_INSTANCE_NAME" >/dev/null 2>&1; then
    echo "The LXC instance $LXD_INSTANCE_NAME already exists."
    while true; do
        read -p "Do you want to recreate it? " yn
        case $yn in
            [Yy]* ) lxc delete $LXD_INSTANCE_NAME --force; break;;
            [Nn]* ) exit;;
            * ) echo "Please answer yes or no.";;
        esac
    done
fi

if ! grep -q $SUBUID /etc/subuid; then
    echo $SUBUID | sudo tee -a /etc/subuid /etc/subgid
fi

lxc init ubuntu:$IMAGE $LXD_INSTANCE_NAME -p default -p $LXD_PROFILE

lxc config set $LXD_INSTANCE_NAME raw.idmap "both $ID $ID"

lxc config device add $LXD_INSTANCE_NAME homedir disk source=$HOME path=/home/ubuntu

lxc start $LXD_INSTANCE_NAME
lxc exec $LXD_INSTANCE_NAME -- cloud-init status --long --wait

# Waiting for the password generation.
sleep 10;

echo "Jenkins password;";

lxc exec $LXD_INSTANCE_NAME -- cat /var/lib/jenkins/secrets/initialAdminPassword

IP=$(lxc exec $LXD_INSTANCE_NAME -- ip addr show eth0 | grep "inet\b" | awk '{print $2}' | cut -d/ -f1)
xdg-open "http://$IP:8080"
