---

- name: Update
  shell: notify-send -a Shack Common "Starting role."
  changed_when: False

- name: Install common core packages
  become: true
  apt:
    name:
      - cmake
      - feh
      - fzf
      - git
      - htop
      - hub
      - jq
      - libinput-dev
      - meson
      - nitrogen
      - postgresql
      - python3-psutil
      - silversearcher-ag
      - tmux
      - util-linux

- name: Git Config
  shell: >-
    git config user.email "dougal@dougalmatthews.com";
    git config user.name "Dougal Matthews"
  changed_when: False

- name: Install Docker
  become: true
  snap:
    name:
      - docker
