---
- name: Install common core packages
  become: true
  apt:
    name:
      - build-essential
      - cloc
      - cmake
      - cpu-checker
      - feh
      - fzf
      - git
      - htop
      - hub
      - jq
      - libinput-dev
      - lxd
      - meson
      - nitrogen
      - postgresql
      - python3-psutil
      - qemu-kvm
      - silversearcher-ag
      - tmux
      - util-linux

- name: Git Config
  shell: >-
    git config user.email "dougal@dougalmatthews.com";
    git config user.name "Dougal Matthews";
    git config --global --replace-all core.editor "vim";
  changed_when: False

- name: Install Docker
  become: true
  snap:
    name:
      - docker

- name: Install juju
  become: true
  snap:
    name:
      - juju
    classic: yes

- name: Install snapcraft
  become: true
  snap:
    name:
      - snapcraft
    classic: yes

- name: Add user to group
  become: true
  user:
    append: yes
    name: dougal
    groups:
      - lxd
