---

- name: Enable git ppa
  become: true
  apt_repository:
    repo: ppa:git-core/ppa

- name: Install common core packages
  become: true
  apt:
    name:
      - bridge-utils
      - brz
      - build-essential
      - cloc
      - cmake
      - cpu-checker
      - devscripts
      - feh
      - fzf
      - git
      - htop
      - hub
      - jq
      - libinput-dev
      - meson
      - nitrogen
      - postgresql
      - python3-psutil
      - qemu-kvm
      - silversearcher-ag
      - tmux
      - util-linux
      - openssh-server

- name: Git Config
  shell: >-
    git config user.email "dougal@dougalmatthews.com";
    git config user.name "Dougal Matthews";
    git config --global --replace-all core.editor "vim";
    git config --global core.excludesfile ~/.gitignore;
    git config --global pull.rebase true;
    git config --global rebase.autoStash true;
  changed_when: False

- copy:
    content: ".vim"
    dest: ~/.gitignore

- name: Install Docker
  become: true
  snap:
    name:
      - docker

- name: Ensure group "docker" exists
  become: true
  group:
    name: docker
    state: present

- name: Add user to docker group
  become: true
  user:
    append: yes
    name: dougal
    groups:
      - docker

- name: Install juju
  become: true
  snap:
    name:
      - juju
    classic: yes

- name: Install snapcraft
  become: true
  snap:
    name:
      - snapcraft
    classic: yes

- name: Bash config file
  copy:
    src: ./templates/bashrc
    dest: ~/.bashrc

- name: ssh config file
  copy:
    src: ./templates/ssh_config
    dest: ~/.ssh/config
