---

- name: Update
  shell: notify-send -a Shack Common "Starting role."
  changed_when: False

- name: Install groups
  become: true
  dnf:
    name:
      - '@Development tools'
      - '@C Development Tools and Libraries'
      - '@Container Management'
      - '@Sound and Video'
      - '@System Tools'
    state: latest

- name: Install common core packages
  become: true
  dnf:
    name:
      - dnf-plugins-core
      - the_silver_searcher
      - util-linux-user
      - cmake
      - libinput-devel
      - git
      - tmux
      - python3-psutil
      - mediawriter
      - chromium
      - meson
      - light
      - feh
      - blueman
      - pavucontrol
    state: latest

- name: RPM Fusion
  become: true
  shell: >
    dnf install -y https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm;
    dnf install -y https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm;
  args:
    warn: false
  changed_when: False

- name: Install non-free
  become: true
  dnf:
    name:
      - dropbox
      - nautilus-dropbox
      - lpf-spotify-client
      - plex-media-player
      - '@Games and Entertainment'
      - steam

- name: Add user to the lpf group
  become: true
  user:
    name: dougal
    group: pkg-build

- name: Install fonts
  become: true
  dnf:
    name:
      - adobe-source-code-pro-fonts
      - fontawesome-fonts
- name: Git Config
  shell: >-
    git config user.email "dougal@dougalmatthews.com";
    git config user.name "Dougal Matthews"
  changed_when: False

- name: Slack client
  become: true
  dnf:
    name:
      - https://downloads.slack-edge.com/linux_releases/slack-4.1.2-0.1.fc21.x86_64.rpm

- name: Add docker repo
  become: true
  shell: >
    dnf config-manager \
      --add-repo \
      https://download.docker.com/linux/fedora/docker-ce.repo
  args:
    warn: false
  changed_when: False

- name: Install Docker
  become: true
  dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose

- name: Start Docker service
  become: true
  systemd:
    state: started
    name: docker
    enabled: true

- name: Add user to the docker group
  become: true
  user:
    name: dougal
    group: docker