---

- name: Enable nvim repo
  package:
    name:
      - https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
  when: ansible_distribution == 'Fedora'

- debug:
    var: ansible_distribution

- name: Install neovim
  become: true
  package:
    name:
      - neovim

- name: Create config directory
  file:
    path: ~/.config/nvim/autoload/
    state: directory
    mode: '0755'

- name: Download vim-plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: ~/.config/nvim/autoload/plug.vim

- name: create init.vim
  copy:
    src: ./templates/init.vim
    dest: ~/.config/nvim/init.vim

- name: Plugin install
  command: nvim +'PlugInstall --sync' +qa
  changed_when: false

- name: Plugin update
  command: nvim +'PlugUpdate --sync' +qa
  changed_when: false
