---

- name: Enable neovim repo
  become: true
  apt_repository:
    repo: ppa:neovim-ppa/unstable

- name: Install neovim
  become: true
  apt:
    name:
      - neovim
      - exuberant-ctags
      - universal-ctags
      - bat

- name: Create config directory
  file:
    path: ~/.config/nvim/autoload/
    state: directory
    mode: '0755'

- name: Download vim-plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: ~/.config/nvim/autoload/plug.vim

- name: create init.vim
  copy:
    src: ./templates/init.vim
    dest: ~/.config/nvim/init.vim

- name: Plugin install
  shell: nvim +'PlugInstall --sync' +qa
  changed_when: False

- name: Plugin update
  shell: nvim +'PlugUpdate --sync' +qa
  changed_when: False
  when:
    - vim_plug_update is defined
    - vim_plug_update|bool
