#!/bin/bash -ex

dir_path=$(dirname $(realpath $0))
source $dir_path/lxd-maas-common

LXD_PROFILE="maas-git"
LXD_INSTANCE_NAME="$DEFAULT_IMAGE-$LXD_PROFILE"

ensure_profile() {
    if ! lxc profile show "$LXD_PROFILE" >/dev/null 2>&1; then
        lxc profile create "$LXD_PROFILE"
    fi

    local uid
    uid=$(id -u "$USER")

    cat <<EOF | lxc profile edit "$LXD_PROFILE"
config:
  user.user-data: |
    #cloud-config
    package_upgrade: true
    packages:
      - build-essential
      - cpu-checker
      - git
      - jq
      - libvirt-clients
      - libvirt-daemon-system
      - qemu-kvm
    runcmd:
     - cat /dev/zero | ssh-keygen -q -N ""
     - cat /root/.ssh/id_rsa.pub >> /root/.ssh/authorized_keys
     - sudo -H -u ubuntu bash -c 'cd ~/code/canonical/maas/ && make install-dependencies'
description: Provide access to /dev/kvm in the container, for hardware accelleration
devices:
  kvm:
    gid: "1001"
    major: "10"
    minor: "232"
    path: /dev/kvm
    type: unix-char
name: maas-git
used_by: []
EOF
}

create_instance(){
    lxc init ubuntu:$DEFAULT_IMAGE $LXD_INSTANCE_NAME -p default -p $LXD_PROFILE
    lxc config set $LXD_INSTANCE_NAME raw.idmap "both $ID $ID"
    lxc config device add $LXD_INSTANCE_NAME homedir disk source=$HOME path=/home/ubuntu
    lxc start $LXD_INSTANCE_NAME

    lxc exec $LXD_INSTANCE_NAME -- cloud-init status --long --wait

}

sync_snap(){
    maas_url
    lxc exec $LXD_INSTANCE_NAME -- su ubuntu -c "cd ~/code/canonical/maas/ && make sync-dev-snap"
    lxc exec $LXD_INSTANCE_NAME -- snap restart maas
}

install_maas_snap(){

    maas_url

    # This is a blatent hack, but cleaning out this directroy before doing the 
    # sync seems to make things much more reliable. ¯\_(ツ)_/¯
    lxc exec $LXD_INSTANCE_NAME -- su ubuntu -c "cd ~/code/canonical/maas/ && rm -rf build/dev-snap/"

    lxc exec $LXD_INSTANCE_NAME -- su ubuntu -c "cd ~/code/canonical/maas/ && make sync-dev-snap"
    lxc exec $LXD_INSTANCE_NAME -- su ubuntu -c "cd ~/code/canonical/maas/ && sudo snap try build/dev-snap/prime"
    lxc exec $LXD_INSTANCE_NAME -- su ubuntu -c "cd ~/code/canonical/maas/ && sudo ./utilities/connect-snap-interfaces"

    maas_init

    maas_createadmin

}


if [ "$1" = "sync" ]; then
    sync_snap
else
    verify_instance_doesnt_exist
    ensure_profile
    create_instance
    create_maas_network
    install_maas_snap
    copy_ssh_keys
    cli_login
    enable_dhcp
    add_kvm_host
    finish
fi
