#!/bin/bash -ex

dir_path=$(dirname $(realpath $0))
source $dir_path/lxd-maas-common

LXD_PROFILE="maas-test"
LXD_INSTANCE_NAME="$DEFAULT_IMAGE-$LXD_PROFILE"


ensure_profile() {
    if ! lxc profile show "$LXD_PROFILE" >/dev/null 2>&1; then
        lxc profile create "$LXD_PROFILE"
    fi

    local uid
    uid=$(id -u "$USER")

    cat <<EOF | lxc profile edit "$LXD_PROFILE"
config:
  user.user-data: |
    #cloud-config
    package_upgrade: true
    packages: [build-essential,git]
    runcmd:
     - cat /dev/zero | ssh-keygen -q -N ""
     - cat /root/.ssh/id_rsa.pub >> /root/.ssh/authorized_keys
     - sudo -H -u ubuntu bash -c 'cd ~/code/maas/ && make install-dependencies'
     - sudo -H -u ubuntu bash -c 'cd ~/code/maas/ && make all'
description: Container with requirements for maas unit tests
name: maas-test
used_by: []
EOF
}

create_instance(){
    lxc init ubuntu:$DEFAULT_IMAGE $LXD_INSTANCE_NAME -p default -p $LXD_PROFILE
    lxc config set $LXD_INSTANCE_NAME raw.idmap "both $ID $ID"
    lxc config device add $LXD_INSTANCE_NAME homedir disk source=$HOME path=/home/ubuntu
    lxc start $LXD_INSTANCE_NAME

    lxc exec $LXD_INSTANCE_NAME -- cloud-init status --long --wait

}


verify_instance_doesnt_exist
ensure_profile
create_instance
