#!/bin/bash -ex

source ./lxd-maas-common

LXD_PROFILE="kvm"
LXD_INSTANCE_NAME="$DEFAULT_IMAGE-maas-virt"

MAAS_SNAP_DEFAULT="--channel=latest/edge maas"


ensure_profile() {
    if ! lxc profile show "$LXD_PROFILE" >/dev/null 2>&1; then
        lxc profile create "$LXD_PROFILE"
    fi

    local uid
    uid=$(id -u "$USER")

    cat <<EOF | lxc profile edit "$LXD_PROFILE"
config:
  user.user-data: |
    #cloud-config
    package_upgrade: true
    packages: [libvirt-bin, qemu-kvm, cpu-checker, libvirt-clients, jq]
    runcmd:
     - cat /dev/zero | ssh-keygen -q -N ""
     - cat /root/.ssh/id_rsa.pub >> /root/.ssh/authorized_keys
description: Provide access to /dev/kvm in the container, for hardware accelleration
devices:
  kvm:
    gid: "1001"
    major: "10"
    minor: "232"
    path: /dev/kvm
    type: unix-char
name: kvm
used_by: []
EOF
}

create_instance(){
    lxc launch ubuntu:$DEFAULT_IMAGE $LXD_INSTANCE_NAME -p default -p $LXD_PROFILE
    lxc exec $LXD_INSTANCE_NAME -- cloud-init status --long --wait

}


install_maas_snap(){
    lxc exec $LXD_INSTANCE_NAME -- snap install $MAAS_SNAP_DEFAULT 

    maas_init

    maas_createadmin
}


verify_instance_doesnt_exist
ensure_profile
create_instance
create_maas_network
install_maas_snap
copy_ssh_keys
cli_login
enable_dhcp
add_kvm_host
finish
