---

- name: Update
  shell: notify-send -a Shack wmcommon "Starting role."
  changed_when: False

- name: Enable Fedora Copr for termite
  become: true
  command: "dnf copr enable -y skidnik/termite"
  args:
    warn: false
  changed_when: False

- name: Install wm packages
  become: true
  dnf:
    name:
      - dunst
      - termite
      - scrot
      - xdotool

- name: Create dunst config directory
  file:
    path: ~/.config/dunst
    state: directory
    mode: '0755'

- name: Dunst config file
  copy:
    src: ./templates/dunstrc
    dest: ~/.config/dunst/dunstrc

- name: Dunst alert script
  copy:
    src: ./templates/alert.py
    dest: ~/.config/dunst/alert.py
    mode: a+x

- name: Kill Dunst
  command: killall dunst
  changed_when: False
  ignore_errors: yes

- name: Install applets
  become: true
  dnf:
    name:
      - network-manager-applet

- name: Create termite config directory
  file:
    path: ~/.config/termite
    state: directory
    mode: '0755'

- name: termite config file
  copy:
    src: ./templates/termite.config
    dest: ~/.config/termite/config
