---

- name: Update
  shell: notify-send -a Shack wmcommon "Starting role."
  changed_when: False

- name: Enable Fedora Copr for termite
  become: true
  command: "dnf copr enable -y skidnik/termite"
  args:
    warn: false
  changed_when: False

- name: Install wm packages
  become: true
  dnf:
    name:
      - dunst
      - termite
      - scrot
      - xdotool
    state: latest

- name: Create dunst config directory
  file:
    path: ~/.config/dunst
    state: directory
    mode: '0755'

- name: Dunst config file
  template:
    src: dunstrc.j2
    dest: ~/.config/dunst/dunstrc

- name: Dunst alert script
  template:
    src: alert.sh.j2
    dest: ~/.config/dunst/alert.sh
    mode: a+x

- name: Kill Dunst
  command: killall dunst
  changed_when: False
  ignore_errors: yes

- name: Install ulauncher
  become: true
  dnf:
    name:
      - https://github.com/Ulauncher/Ulauncher/releases/download/5.4.0/ulauncher_5.4.0_fedora29.rpm
    state: latest

- name: Install applets
  become: true
  dnf:
    name:
      - network-manager-applet

- name: Create termite config directory
  file:
    path: ~/.config/termite
    state: directory
    mode: '0755'

- name: termite config file
  template:
    src: termite.config.j2
    dest: ~/.config/termite/config
