#!/bin/bash

set -xe;

SCREEN_DIR=~/Dropbox/Screenshots/`date +%Y/%m`/
mkdir $SCREEN_DIR -p
SCREEN_PROMPT=1

window='root'

case $1 in
  root)
    window='root';;
  active)
    window=`xprop -root | grep "_NET_ACTIVE_WINDOW(WINDOW)" | cut -d' ' -f5`;;
  imgur)
    window=`xprop -root | grep "_NET_ACTIVE_WINDOW(WINDOW)" | cut -d' ' -f5`;;
esac

if [ -z "$name" ];then
  if [ $window == "root" ];then
    name=''
  else
    name=`xprop -id $window | sed -n '/WM_CLASS/s/.* = "\([^\"]*\)".*/\1\n/p'`
    [ -z "$name" ] && name='window'
    name=".$name"
  fi
fi

filename="Screenshot `date +%Y-%m-%d-%H.%M.%S`$name.png"

import -border -window $window "$SCREEN_DIR/$filename"



clientid='c9c967af714514a'
clientsecret='1fd36541e365c1f3ba95be18b3334aea0220ffd6'

xclip -sel clip -i /dev/null;

if [ "$1" = "imgur" ];then
  res=$(curl -sH "Authorization: Client-ID $clientid" -F "image=@$SCREEN_DIR/$filename" "https://api.imgur.com/3/upload")
  echo $res
  echo $res | grep -qo '"status":200' && link=$(echo $res | sed -e 's/.*"link":"\([^"]*\).*/\1/' -e 's/\\//g')
else
  link=$(dropbox sharelink "$SCREEN_DIR/$filename");
fi

echo "$link" >> ~/Dropbox/screenshot-log.txt;
notify-send -u critical -a "Screenshot" "$link";
echo "$link";
echo "$link" | xclip -sel clip;
firefox "$link";

exit
