#!/bin/sh
xrandr --output eDP-1 --off --output DP-1-2 --mode 1920x1200 --pos 0x240 --rotate left --output HDMI-2 --off --output HDMI-1 --off --output DP-1 --off --output DP-1-3 --mode 1920x1200 --pos 5040x240 --rotate left --output DP-2 --off --output DP-1-1 --mode 3840x2160 --pos 1200x0 --rotate normal

i3-msg restart;