#!/bin/sh

EU=`env TZ=Europe/Prague date`
UTC=`env TZ=UTC date`
UK=`env TZ=Europe/London date`
ET=`env TZ=US/Eastern date`
PT=`env TZ=US/Pacific date`

echo "Brno                  $EU"
echo "UTC                   $UTC"
echo "Home                  $UK"
echo "Raleigh, NC           $ET"
echo "Mountain View, CA     $PT"
