---

- name: Install Snaps
  become: true
  snap:
    name:
      - maas

- name: Copy over lxd scripts
  copy:
    src: "{{ item }}"
    dest: ~/bin/{{ item | basename | regex_replace('\.j2','') }}
    mode: a+x
  with_fileglob:
    - ../templates/*
